name: Create Pull Request for Release Branch

on:
  push:
    branches:
      - "release/**"

jobs:
  create_pr:
    env:
      RELEASE_VERSION: null

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get the version
        run: |
          VERSION=$(cargo pkgid | awk -F# '{print $2}')
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ github.ref_name }}
          base: main
          title: "v${{ env.RELEASE_VERSION }}"
          body: |
            This pull request is automatically created for the release branch: ${{ github.ref_name }}.
